resources:
  root: file:C:/etc/secret
  driver-class: org.postgresql.Driver
  path:
    admin-endpoint: /ADMIN_ENDPOINT
    admin-username: /ADMIN_USERNAME
    admin-password: /ADMIN_PASSWORD
    admin-database: /ADMIN_DATABASE
    admin-schema: /ADMIN_SCHEMA
    redis-endpoint: /REDIS_ENDPOINT

spring:
  profiles:
    active: default

  datasource:
    hikari:
      minimum-idle: 50
      maximum-pool-size: 50

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    # throw-exception-if-no-handler-found: true

  # if you want to use hibernate, please use this
  # jpa:
  #   hibernate:
  #     ddl-auto: none
  #   properties.hibernate.temp.use_jdbc_metadata_defaults: false
  #   properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: 7071
  tomcat:
    threads:
      max: 512
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

#mybatis
mybatis:
  type-aliases-package: com.lguplus.ukids.admin.repository
  mapper-locations: classpath:sql/*.xml
  configuration:
    map-underscore-to-camel-case: true

feign:
  httpclient:
    disableSslValidation: true
  client:
    config:
      default:
        connect-timeout: 30000
        read-timeout: 30000
        loggerLevel: FULL

cloud:
  aws:
    region: ap-northeast-2
    s3:
      session-time: 300000

---
spring:
  profiles: default
  redis:
    port: 6379
    ttl: 3000

cloud:
  aws:
    s3:
      public-bucket: ukids-dev-s3-public
      private-bucket: ukids-dev-s3-private

logging:
  level:
    com.lguplus.ukids.admin: debug

---
spring:
  profiles: dev
  redis:
    port: 6379
    ttl: 3000

cloud:
  aws:
    s3:
      public-bucket: ukids-dev-s3-public
      private-bucket: ukids-dev-s3-private

logging:
  level:
    com.lguplus.ukids.admin: debug

---
spring:
  profiles: stg
  redis:
    port: 6379
    ttl: 3000

cloud:
  aws:
    s3:
      public-bucket: ukids-stg-s3-public
      private-bucket: ukids-stg-s3-private

logging:
  level:
    com.lguplus.ukids.admin: info

---
spring:
  profiles: prd
  redis:
    port: 6379
    ttl: 3000

cloud:
  aws:
    s3:
      public-bucket: ukids-prd-s3-public
      private-bucket: ukids-prd-s3-private

logging:
  level:
    com.lguplus.ukids.admin: info
